## Assignments


## Day 1

### Assignment 1-> Matrix transpose using with and without built in function

In [9]:
#without builtin function
matrix=[
    [1,2,3,4],
    [6,8,3,4],
    [7,8,9,3]
]
transpose=[[row[i] for row in matrix] for i in range(len(matrix)+1)]
print(transpose)

#with builtin function
import numpy as np
print(np.array(matrix).T)

[[1, 6, 7], [2, 8, 8], [3, 3, 9], [4, 4, 3]]
[[1 6 7]
 [2 8 8]
 [3 3 9]
 [4 4 3]]


### Assignment2-> share elements without sharing address

In [10]:
lst1=[1,2,3,4,5,5]
lst2=lst1.copy()
print("Lst1->",id(lst1))
print("lst2->",id(lst2))

Lst1-> 1537166202112
lst2-> 1537165364416


### Assignment3 ->: How to reassign the data that is temporarily deleted

In [11]:
lst={
    "name":'Ram',
    "age":22,
    "salary":45000
}
salary=lst.pop('salary')
print(lst)

#reassigning
lst['salary']=salary
print(lst)

{'name': 'Ram', 'age': 22}
{'name': 'Ram', 'age': 22, 'salary': 45000}


## Day2

### Assignment 1-> why we cant call the local variable from outside the function

Because a local variable only exits inside the function's scope.
When we create a variable inside a function,Python treats it as private to that function.outside the f
function ,Python literally doesnt know that variable exists

### Assigment 2-> Where to use Map,Filter,Reduce

In [1]:
# map() function is used to transform every elements,like it modifies the elements based
#on the given function

lst=[1,2,3,4,5]
lst1=list(map(lambda x:x**2,lst))
print(lst1)

[1, 4, 9, 16, 25]


In [2]:
#filter() function is used to filter the elements from the list ,we only 
#keep the elements that matches with the condition 

lst2=list(filter(lambda x:x&1,lst)) # getting only the odd numbers
print(lst2)

[1, 3, 5]


In [3]:
#Reduce() function help us to Collapse the list values into single value,used when we 
#need one final result
from functools import reduce
cumi_sum=reduce(lambda x,y:x+y,lst)
print(cumi_sum)

15
